import 'package:aigammon_app/data/database.dart';
import 'package:drift/drift.dart' show Value;
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:sqlite3/sqlite3.dart';

/// The exact v1 schema DDL (matches + games), as generated by drift at
/// schemaVersion 1 — before the v2 `settings` table existed. Embedded as a
/// constant so this test can materialise a genuine v1 database (raw sqlite3),
/// then open it through [AppDatabase] and prove the 1 -> N `onUpgrade` runs.
///
/// Column names/types mirror drift's output for the current `Matches`/`Games`
/// table definitions (unchanged since v1), so v1 rows round-trip after upgrade.
const _v1MatchesDdl = '''
CREATE TABLE "matches" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "created_at" INTEGER NOT NULL,
  "match_length" INTEGER NOT NULL,
  "mode" TEXT NOT NULL,
  "white_type" TEXT NOT NULL,
  "black_type" TEXT NOT NULL,
  "white_score" INTEGER NOT NULL DEFAULT 0,
  "black_score" INTEGER NOT NULL DEFAULT 0,
  "winner" TEXT NULL,
  "completed" INTEGER NOT NULL DEFAULT 0 CHECK ("completed" IN (0, 1))
);
''';

const _v1GamesDdl = '''
CREATE TABLE "games" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "match_id" INTEGER NOT NULL REFERENCES matches (id) ON DELETE CASCADE,
  "game_number" INTEGER NOT NULL,
  "is_crawford" INTEGER NOT NULL CHECK ("is_crawford" IN (0, 1)),
  "events_json" TEXT NOT NULL,
  "result_winner" TEXT NULL,
  "result_points" INTEGER NULL,
  "result_outcome" TEXT NULL,
  "analysis_json" TEXT NULL
);
''';

/// The exact v2 `settings` DDL — as drift generated it at schemaVersion 2,
/// BEFORE the v3 gameplay-option columns, the v4 `drag_hint_shown` column and
/// the v5 `dice_roll_animation` column existed. Embedded so this test can
/// materialise a genuine v2 database and prove the 2 -> 7 `onUpgrade` adds every
/// later column.
const _v2SettingsDdl = '''
CREATE TABLE "settings" (
  "id" INTEGER NOT NULL DEFAULT 1,
  "theme_mode" TEXT NOT NULL DEFAULT 'system',
  "animation_speed" TEXT NOT NULL DEFAULT 'normal',
  "default_match_length" INTEGER NOT NULL DEFAULT 5,
  "default_difficulty" TEXT NOT NULL DEFAULT 'medium',
  "tutor_override" TEXT NULL,
  PRIMARY KEY ("id"),
  CHECK (id = 1)
);
''';

/// The exact v3 `settings` DDL — as drift generated it at schemaVersion 3. It
/// carries the four gameplay columns (`show_highlights`, `enable_drag`,
/// `enable_combined_taps`, `show_scoring`) but NEITHER the v4 `drag_hint_shown`
/// nor the v5 `dice_roll_animation` column, and crucially `enable_drag` still
/// defaults to 0 (OFF) as it did in v3. Embedded so this test can materialise a
/// genuine v3 database and prove the 3 -> 5 `onUpgrade` adds both later columns
/// AND flips `enable_drag` to 1.
const _v3SettingsDdl = '''
CREATE TABLE "settings" (
  "id" INTEGER NOT NULL DEFAULT 1,
  "theme_mode" TEXT NOT NULL DEFAULT 'system',
  "animation_speed" TEXT NOT NULL DEFAULT 'normal',
  "default_match_length" INTEGER NOT NULL DEFAULT 5,
  "default_difficulty" TEXT NOT NULL DEFAULT 'medium',
  "tutor_override" TEXT NULL,
  "show_highlights" INTEGER NOT NULL DEFAULT 1 CHECK ("show_highlights" IN (0, 1)),
  "enable_drag" INTEGER NOT NULL DEFAULT 0 CHECK ("enable_drag" IN (0, 1)),
  "enable_combined_taps" INTEGER NOT NULL DEFAULT 1 CHECK ("enable_combined_taps" IN (0, 1)),
  "show_scoring" INTEGER NOT NULL DEFAULT 1 CHECK ("show_scoring" IN (0, 1)),
  PRIMARY KEY ("id"),
  CHECK (id = 1)
);
''';

/// The exact v4 `settings` DDL — as drift generated it at schemaVersion 4: the
/// four gameplay columns plus `drag_hint_shown`, with `enable_drag` already
/// defaulting to 1 (the v4 flip), but WITHOUT the v5 `dice_roll_animation`
/// column. Embedded so this test can materialise a genuine v4 database and prove
/// the 4 -> 5 `onUpgrade` adds that column (defaulting ON) and touches nothing
/// else — in particular that it does NOT re-run the v4 drag flip.
const _v4SettingsDdl = '''
CREATE TABLE "settings" (
  "id" INTEGER NOT NULL DEFAULT 1,
  "theme_mode" TEXT NOT NULL DEFAULT 'system',
  "animation_speed" TEXT NOT NULL DEFAULT 'normal',
  "default_match_length" INTEGER NOT NULL DEFAULT 5,
  "default_difficulty" TEXT NOT NULL DEFAULT 'medium',
  "tutor_override" TEXT NULL,
  "show_highlights" INTEGER NOT NULL DEFAULT 1 CHECK ("show_highlights" IN (0, 1)),
  "enable_drag" INTEGER NOT NULL DEFAULT 1 CHECK ("enable_drag" IN (0, 1)),
  "enable_combined_taps" INTEGER NOT NULL DEFAULT 1 CHECK ("enable_combined_taps" IN (0, 1)),
  "show_scoring" INTEGER NOT NULL DEFAULT 1 CHECK ("show_scoring" IN (0, 1)),
  "drag_hint_shown" INTEGER NOT NULL DEFAULT 0 CHECK ("drag_hint_shown" IN (0, 1)),
  PRIMARY KEY ("id"),
  CHECK (id = 1)
);
''';

/// The exact v5 `settings` DDL — as drift generated it at schemaVersion 5:
/// everything v4 had plus `dice_roll_animation`, but WITHOUT the v6
/// `show_pass_device` column.
///
/// v5 was never released, but it WAS built and run on development machines, so
/// a v5 database on disk is a real shape the app has to migrate. Embedded so
/// this test can materialise one and prove the 5 -> 7 `onUpgrade` adds the
/// missing column rather than leaving the app writing into a column that is not
/// there (the failure that motivated the v6 bump).
const _v5SettingsDdl = '''
CREATE TABLE "settings" (
  "id" INTEGER NOT NULL DEFAULT 1,
  "theme_mode" TEXT NOT NULL DEFAULT 'system',
  "animation_speed" TEXT NOT NULL DEFAULT 'normal',
  "default_match_length" INTEGER NOT NULL DEFAULT 5,
  "default_difficulty" TEXT NOT NULL DEFAULT 'medium',
  "tutor_override" TEXT NULL,
  "show_highlights" INTEGER NOT NULL DEFAULT 1 CHECK ("show_highlights" IN (0, 1)),
  "enable_drag" INTEGER NOT NULL DEFAULT 1 CHECK ("enable_drag" IN (0, 1)),
  "enable_combined_taps" INTEGER NOT NULL DEFAULT 1 CHECK ("enable_combined_taps" IN (0, 1)),
  "show_scoring" INTEGER NOT NULL DEFAULT 1 CHECK ("show_scoring" IN (0, 1)),
  "dice_roll_animation" INTEGER NOT NULL DEFAULT 1 CHECK ("dice_roll_animation" IN (0, 1)),
  "drag_hint_shown" INTEGER NOT NULL DEFAULT 0 CHECK ("drag_hint_shown" IN (0, 1)),
  PRIMARY KEY ("id"),
  CHECK (id = 1)
);
''';

/// The exact v6 `settings` DDL — as drift generated it at schemaVersion 6:
/// everything v5 had plus `show_pass_device`, but WITHOUT the v7
/// `rotate_board_hot_seat` column. The shape currently on every tester's device,
/// so this is the upgrade path that actually matters for the tabletop hot-seat
/// change; without the 6 -> 7 branch a settings save would throw "table settings
/// has no column named rotate_board_hot_seat".
const _v6SettingsDdl = '''
CREATE TABLE "settings" (
  "id" INTEGER NOT NULL DEFAULT 1,
  "theme_mode" TEXT NOT NULL DEFAULT 'system',
  "animation_speed" TEXT NOT NULL DEFAULT 'normal',
  "default_match_length" INTEGER NOT NULL DEFAULT 5,
  "default_difficulty" TEXT NOT NULL DEFAULT 'medium',
  "tutor_override" TEXT NULL,
  "show_highlights" INTEGER NOT NULL DEFAULT 1 CHECK ("show_highlights" IN (0, 1)),
  "enable_drag" INTEGER NOT NULL DEFAULT 1 CHECK ("enable_drag" IN (0, 1)),
  "enable_combined_taps" INTEGER NOT NULL DEFAULT 1 CHECK ("enable_combined_taps" IN (0, 1)),
  "show_scoring" INTEGER NOT NULL DEFAULT 1 CHECK ("show_scoring" IN (0, 1)),
  "dice_roll_animation" INTEGER NOT NULL DEFAULT 1 CHECK ("dice_roll_animation" IN (0, 1)),
  "show_pass_device" INTEGER NOT NULL DEFAULT 0 CHECK ("show_pass_device" IN (0, 1)),
  "drag_hint_shown" INTEGER NOT NULL DEFAULT 0 CHECK ("drag_hint_shown" IN (0, 1)),
  PRIMARY KEY ("id"),
  CHECK (id = 1)
);
''';

/// The exact v7 `settings` DDL — as drift generated it at schemaVersion 7:
/// v6 plus `rotate_board_hot_seat` (between `show_pass_device` and
/// `drag_hint_shown`, which is where the generated column order puts it).
///
/// This is the shape EVERY currently installed build is on, so 7 -> 8 is the
/// migration every real upgrade actually takes. v8 adds no settings column at
/// all — it creates the `online_session` table — which is exactly why it is
/// worth pinning: a branch that silently did nothing would look like a pass.
const _v7SettingsDdl = '''
CREATE TABLE "settings" (
  "id" INTEGER NOT NULL DEFAULT 1,
  "theme_mode" TEXT NOT NULL DEFAULT 'system',
  "animation_speed" TEXT NOT NULL DEFAULT 'normal',
  "default_match_length" INTEGER NOT NULL DEFAULT 5,
  "default_difficulty" TEXT NOT NULL DEFAULT 'medium',
  "tutor_override" TEXT NULL,
  "show_highlights" INTEGER NOT NULL DEFAULT 1 CHECK ("show_highlights" IN (0, 1)),
  "enable_drag" INTEGER NOT NULL DEFAULT 1 CHECK ("enable_drag" IN (0, 1)),
  "enable_combined_taps" INTEGER NOT NULL DEFAULT 1 CHECK ("enable_combined_taps" IN (0, 1)),
  "show_scoring" INTEGER NOT NULL DEFAULT 1 CHECK ("show_scoring" IN (0, 1)),
  "dice_roll_animation" INTEGER NOT NULL DEFAULT 1 CHECK ("dice_roll_animation" IN (0, 1)),
  "show_pass_device" INTEGER NOT NULL DEFAULT 0 CHECK ("show_pass_device" IN (0, 1)),
  "rotate_board_hot_seat" INTEGER NOT NULL DEFAULT 0 CHECK ("rotate_board_hot_seat" IN (0, 1)),
  "drag_hint_shown" INTEGER NOT NULL DEFAULT 0 CHECK ("drag_hint_shown" IN (0, 1)),
  PRIMARY KEY ("id"),
  CHECK (id = 1)
);
''';

void main() {
  test(
      'fresh install (onCreate) seeds v7 defaults: drag ON, dice roll animation '
      'ON, pass-device cover OFF, hot-seat board rotation OFF, hint not shown',
      () async {
    // A brand-new database goes through onCreate (not onUpgrade): the v7 table
    // shape + the beforeOpen seed.
    final db = AppDatabase(NativeDatabase.memory());

    final settings = await db.select(db.settings).getSingle();
    expect(settings.enableDrag, isTrue,
        reason: 'drag-to-move is ON by default as of v4');
    expect(settings.diceRollAnimation, isTrue,
        reason: 'the dice roll tumbles by default as of v5');
    expect(settings.showPassDevice, isFalse,
        reason: 'the hot-seat cover screen is OFF by default as of v6');
    expect(settings.rotateBoardHotSeat, isFalse,
        reason: 'hot-seat keeps the board FIXED by default as of v7 — the '
            'tabletop layout, an action bar at each player edge');
    expect(settings.dragHintShown, isFalse,
        reason: 'the one-time hint has not been shown yet on a fresh install');
    expect(settings.showHighlights, isTrue);
    expect(settings.enableCombinedTaps, isTrue);
    expect(settings.showScoring, isTrue);

    final version = await db.customSelect('PRAGMA user_version').getSingle();
    expect(version.read<int>('user_version'), 8);

    await db.close();
  });

  test('1 -> 8 upgrade creates the settings table whole (v7 shape: drag ON, '
      'drag_hint_shown + dice_roll_animation + show_pass_device + '
      'rotate_board_hot_seat present), seeds it, and preserves v1 data',
      () async {
    // 1. Build a genuine v1 database: the v1 tables, a real match row, and
    //    user_version = 1.
    final raw = sqlite3.openInMemory();
    raw.execute(_v1MatchesDdl);
    raw.execute(_v1GamesDdl);
    raw.execute(
      'INSERT INTO matches (created_at, match_length, mode, white_type, '
      "black_type) VALUES (1700000000, 5, 'vsComputer', 'human', 'ai:expert')",
    );
    raw.execute('PRAGMA user_version = 1');

    // Sanity: no settings table yet at v1.
    final before = raw.select(
        "SELECT name FROM sqlite_master WHERE type='table' AND name='settings'");
    expect(before, isEmpty, reason: 'v1 has no settings table');

    // 2. Open the SAME database through AppDatabase (schemaVersion 8). drift
    //    sees user_version 1 and runs onUpgrade(1 -> 8), then beforeOpen.
    final db = AppDatabase(NativeDatabase.opened(raw));

    // 3a. The settings table now exists with the single default row — including
    //     the v7 shape: drag ON, the dice beat ON, no cover screen, a fixed
    //     hot-seat board, no hint.
    final settings = await db.select(db.settings).getSingle();
    expect(settings.id, 1);
    expect(settings.themeMode, 'system');
    expect(settings.animationSpeed, 'normal');
    expect(settings.defaultMatchLength, 5);
    expect(settings.defaultDifficulty, 'medium');
    expect(settings.tutorOverride, isNull);
    expect(settings.showHighlights, isTrue);
    expect(settings.enableDrag, isTrue, reason: 'v4 default flips drag ON');
    expect(settings.enableCombinedTaps, isTrue);
    expect(settings.showScoring, isTrue);
    expect(settings.dragHintShown, isFalse);
    expect(settings.diceRollAnimation, isTrue);
    expect(settings.showPassDevice, isFalse);
    expect(settings.rotateBoardHotSeat, isFalse);

    // 3b. The pre-migration v1 match row survived intact.
    final matches = await db.select(db.matches).get();
    expect(matches, hasLength(1));
    expect(matches.single.mode, 'vsComputer');
    expect(matches.single.matchLength, 5);
    expect(matches.single.whiteType, 'human');
    expect(matches.single.blackType, 'ai:expert');

    // 3c. The schema version was bumped to 7.
    final version = await db.customSelect('PRAGMA user_version').getSingle();
    expect(version.read<int>('user_version'), 8);

    // 3d. Writes still work post-migration (FK/insert into the migrated schema).
    final newId = await db.into(db.matches).insert(MatchesCompanion.insert(
          createdAt: DateTime.now(),
          matchLength: 3,
          mode: 'hotSeat',
          whiteType: 'human',
          blackType: 'human',
          whiteScore: const Value(0),
        ));
    expect(newId, greaterThan(matches.single.id));

    await db.close();
  });

  test('2 -> 8 upgrade adds the gameplay + drag_hint_shown + '
      'dice_roll_animation + show_pass_device + rotate_board_hot_seat columns, '
      'flips drag ON, and preserves the existing v2 settings row values',
      () async {
    // 1. Build a genuine v2 database: the matches/games tables (unchanged), the
    //    v2 settings table, a settings row with NON-default preferences, and
    //    user_version = 2.
    final raw = sqlite3.openInMemory();
    raw.execute(_v1MatchesDdl);
    raw.execute(_v1GamesDdl);
    raw.execute(_v2SettingsDdl);
    raw.execute(
      'INSERT INTO settings (id, theme_mode, animation_speed, '
      'default_match_length, default_difficulty, tutor_override) '
      "VALUES (1, 'dark', 'off', 7, 'expert', 'on')",
    );
    raw.execute('PRAGMA user_version = 2');

    // Sanity: the v2 settings table has none of the later columns yet.
    final cols = raw
        .select('PRAGMA table_info(settings)')
        .map((r) => r['name'] as String)
        .toSet();
    expect(cols, isNot(contains('show_highlights')), reason: 'v2 has no v3 cols');
    expect(cols, isNot(contains('enable_drag')));
    expect(cols, isNot(contains('drag_hint_shown')), reason: 'nor the v4 col');
    expect(cols, isNot(contains('dice_roll_animation')),
        reason: 'nor the v5 col');
    expect(cols, isNot(contains('show_pass_device')));
    expect(cols, isNot(contains('rotate_board_hot_seat')),
        reason: 'nor the v7 col');

    // 2. Open through AppDatabase (schemaVersion 8): drift runs onUpgrade(2 -> 8),
    //    adding the four gameplay columns + drag_hint_shown +
    //    dice_roll_animation + show_pass_device + rotate_board_hot_seat, then
    //    flipping drag.
    final db = AppDatabase(NativeDatabase.opened(raw));

    // 3a. The new columns exist at their v7 defaults on the migrated row —
    //     including drag flipped ON, the dice beat ON, the hint not yet shown
    //     and the hot-seat board left unrotated.
    final settings = await db.select(db.settings).getSingle();
    expect(settings.showHighlights, isTrue);
    expect(settings.enableDrag, isTrue, reason: 'the v4 flip turns drag ON');
    expect(settings.enableCombinedTaps, isTrue);
    expect(settings.showScoring, isTrue);
    expect(settings.dragHintShown, isFalse);
    expect(settings.diceRollAnimation, isTrue,
        reason: 'the v5 column defaults ON for an upgraded row too');
    expect(settings.showPassDevice, isFalse,
        reason: 'the v6 column defaults OFF for an upgraded row too');
    expect(settings.rotateBoardHotSeat, isFalse,
        reason: 'and the v7 column lands on the tabletop default');

    // 3b. The pre-existing v2 settings row values SURVIVED intact.
    expect(settings.id, 1);
    expect(settings.themeMode, 'dark');
    expect(settings.animationSpeed, 'off');
    expect(settings.defaultMatchLength, 7);
    expect(settings.defaultDifficulty, 'expert');
    expect(settings.tutorOverride, 'on');

    // 3c. The schema version was bumped to 7, and still exactly one row.
    final version = await db.customSelect('PRAGMA user_version').getSingle();
    expect(version.read<int>('user_version'), 8);
    expect(await db.select(db.settings).get(), hasLength(1));

    await db.close();
  });

  test('3 -> 8 upgrade adds drag_hint_shown (=false) + dice_roll_animation '
      '(=true) + show_pass_device (=false) + rotate_board_hot_seat (=false) and '
      'flips a user-OFF enable_drag to ON, preserving every other v3 value',
      () async {
    // 1. Build a genuine v3 database: matches/games + the v3 settings table with
    //    a row where the user deliberately turned drag OFF (enable_drag = 0) and
    //    tweaked other preferences. user_version = 3.
    final raw = sqlite3.openInMemory();
    raw.execute(_v1MatchesDdl);
    raw.execute(_v1GamesDdl);
    raw.execute(_v3SettingsDdl);
    raw.execute(
      'INSERT INTO settings (id, theme_mode, animation_speed, '
      'default_match_length, default_difficulty, tutor_override, '
      'show_highlights, enable_drag, enable_combined_taps, show_scoring) '
      "VALUES (1, 'dark', 'fast', 3, 'hard', 'off', 0, 0, 0, 0)",
    );
    raw.execute('PRAGMA user_version = 3');

    // Sanity: the v3 settings table has enable_drag (set OFF) but not the v4
    // drag_hint_shown column yet.
    final cols = raw
        .select('PRAGMA table_info(settings)')
        .map((r) => r['name'] as String)
        .toSet();
    expect(cols, contains('enable_drag'), reason: 'v3 has the gameplay cols');
    expect(cols, isNot(contains('drag_hint_shown')),
        reason: 'v3 predates the drag-hint column');
    expect(cols, isNot(contains('dice_roll_animation')),
        reason: 'v3 predates the dice-roll-animation column');
    expect(cols, isNot(contains('show_pass_device')),
        reason: 'v3 predates the pass-device column');
    expect(cols, isNot(contains('rotate_board_hot_seat')),
        reason: 'v3 predates the hot-seat rotation column');

    // 2. Open through AppDatabase (schemaVersion 8): drift runs onUpgrade(3 -> 8),
    //    which addColumn's the three later columns and UPDATEs enable_drag = 1.
    final db = AppDatabase(NativeDatabase.opened(raw));

    // 3a. Both later columns now exist at their defaults; enable_drag was flipped
    //     from the user's OFF back to ON (the one-time default flip).
    final settings = await db.select(db.settings).getSingle();
    expect(settings.dragHintShown, isFalse,
        reason: 'the drag_hint_shown column exists and starts false');
    expect(settings.diceRollAnimation, isTrue,
        reason: 'the dice_roll_animation column exists and starts ON');
    expect(settings.showPassDevice, isFalse,
        reason: 'the show_pass_device column exists and starts OFF');
    expect(settings.rotateBoardHotSeat, isFalse,
        reason: 'the rotate_board_hot_seat column exists and starts OFF');
    expect(settings.enableDrag, isTrue,
        reason: 'the v4 upgrade flips a user-disabled drag back ON (one-time)');

    // 3b. Every OTHER v3 value survived untouched — the flip is surgical.
    expect(settings.themeMode, 'dark');
    expect(settings.animationSpeed, 'fast');
    expect(settings.defaultMatchLength, 3);
    expect(settings.defaultDifficulty, 'hard');
    expect(settings.tutorOverride, 'off');
    expect(settings.showHighlights, isFalse);
    expect(settings.enableCombinedTaps, isFalse);
    expect(settings.showScoring, isFalse);

    // 3c. The schema version was bumped to 7, still exactly one row.
    final version = await db.customSelect('PRAGMA user_version').getSingle();
    expect(version.read<int>('user_version'), 8);
    expect(await db.select(db.settings).get(), hasLength(1));

    // 3d. Writes still work post-migration (upsert the migrated settings row).
    await db.into(db.settings).insertOnConflictUpdate(
        SettingsCompanion(id: const Value(1), dragHintShown: const Value(true)));
    expect((await db.select(db.settings).getSingle()).dragHintShown, isTrue);

    await db.close();
  });

  test('4 -> 8 upgrade adds dice_roll_animation (=true) + show_pass_device '
      '(=false) + rotate_board_hot_seat (=false) and changes nothing else — no '
      're-run of the v4 drag flip', () async {
    // 1. Build a genuine v4 database: matches/games + the v4 settings table with
    //    a row where the user turned drag OFF *after* the v4 flip had already
    //    run, and tweaked other preferences. user_version = 4.
    final raw = sqlite3.openInMemory();
    raw.execute(_v1MatchesDdl);
    raw.execute(_v1GamesDdl);
    raw.execute(_v4SettingsDdl);
    raw.execute(
      'INSERT INTO settings (id, theme_mode, animation_speed, '
      'default_match_length, default_difficulty, tutor_override, '
      'show_highlights, enable_drag, enable_combined_taps, show_scoring, '
      'drag_hint_shown) '
      "VALUES (1, 'dark', 'fast', 7, 'expert', 'off', 1, 0, 0, 0, 1)",
    );
    raw.execute('PRAGMA user_version = 4');

    // Sanity: the v4 settings table has drag_hint_shown but not the v5 column.
    final cols = raw
        .select('PRAGMA table_info(settings)')
        .map((r) => r['name'] as String)
        .toSet();
    expect(cols, contains('drag_hint_shown'), reason: 'v4 has the hint column');
    expect(cols, isNot(contains('dice_roll_animation')),
        reason: 'v4 predates the dice-roll-animation column');
    expect(cols, isNot(contains('show_pass_device')),
        reason: 'v4 predates the pass-device column');

    // 2. Open through AppDatabase (schemaVersion 8): drift runs onUpgrade(4 -> 8),
    //    which only addColumn's the two later columns.
    final db = AppDatabase(NativeDatabase.opened(raw));

    // 3a. The new columns exist at their defaults on the migrated row.
    final settings = await db.select(db.settings).getSingle();
    expect(settings.diceRollAnimation, isTrue,
        reason: 'an upgrading user gets the dice beat, like a fresh install');
    expect(settings.showPassDevice, isFalse,
        reason: 'and no pass-device cover, like a fresh install');
    expect(settings.rotateBoardHotSeat, isFalse,
        reason: 'and a fixed hot-seat board, like a fresh install');

    // 3b. Every v4 value survived — crucially the user's OFF drag is NOT flipped
    //     again (the one-time v4 flip is gated on `from < 4`).
    expect(settings.enableDrag, isFalse,
        reason: 'the v4 drag flip must never re-run on a v4 -> v7 upgrade');
    expect(settings.themeMode, 'dark');
    expect(settings.animationSpeed, 'fast');
    expect(settings.defaultMatchLength, 7);
    expect(settings.defaultDifficulty, 'expert');
    expect(settings.tutorOverride, 'off');
    expect(settings.showHighlights, isTrue);
    expect(settings.enableCombinedTaps, isFalse);
    expect(settings.showScoring, isFalse);
    expect(settings.dragHintShown, isTrue,
        reason: 'a hint already shown stays shown');

    // 3c. The schema version was bumped to 7, still exactly one row.
    final version = await db.customSelect('PRAGMA user_version').getSingle();
    expect(version.read<int>('user_version'), 8);
    expect(await db.select(db.settings).get(), hasLength(1));

    // 3d. Writes still work post-migration (upsert the migrated settings row).
    await db.into(db.settings).insertOnConflictUpdate(SettingsCompanion(
        id: const Value(1), diceRollAnimation: const Value(false)));
    expect((await db.select(db.settings).getSingle()).diceRollAnimation,
        isFalse);

    await db.close();
  });
  test('5 -> 8 upgrade adds show_pass_device (=false) + rotate_board_hot_seat '
      '(=false) and preserves every v5 value — the unreleased-but-installed '
      'shape', () async {
    // 1. Build a genuine v5 database: matches/games + the v5 settings table with
    //    a row the user had already edited. user_version = 5.
    final raw = sqlite3.openInMemory();
    raw.execute(_v1MatchesDdl);
    raw.execute(_v1GamesDdl);
    raw.execute(_v5SettingsDdl);
    raw.execute(
      'INSERT INTO settings (id, theme_mode, animation_speed, '
      'default_match_length, default_difficulty, tutor_override, '
      'show_highlights, enable_drag, enable_combined_taps, show_scoring, '
      'dice_roll_animation, drag_hint_shown) '
      "VALUES (1, 'light', 'fast', 3, 'easy', 'on', 0, 1, 1, 1, 0, 1)",
    );
    raw.execute('PRAGMA user_version = 5');

    final cols = raw
        .select('PRAGMA table_info(settings)')
        .map((r) => r['name'] as String)
        .toSet();
    expect(cols, contains('dice_roll_animation'), reason: 'v5 has the beat col');
    expect(cols, isNot(contains('show_pass_device')),
        reason: 'v5 predates the pass-device column');

    // 2. Open through AppDatabase (schemaVersion 8): onUpgrade(5 -> 8).
    final db = AppDatabase(NativeDatabase.opened(raw));

    // 3a. The column exists at its default, so a settings SAVE no longer throws
    //     "table settings has no column named show_pass_device".
    final settings = await db.select(db.settings).getSingle();
    expect(settings.showPassDevice, isFalse);
    expect(settings.rotateBoardHotSeat, isFalse);

    // 3b. Every v5 value survived — including a deliberately-off dice beat and
    //     an already-shown drag hint.
    expect(settings.themeMode, 'light');
    expect(settings.animationSpeed, 'fast');
    expect(settings.defaultMatchLength, 3);
    expect(settings.defaultDifficulty, 'easy');
    expect(settings.tutorOverride, 'on');
    expect(settings.showHighlights, isFalse);
    expect(settings.enableDrag, isTrue);
    expect(settings.diceRollAnimation, isFalse,
        reason: 'a user-disabled beat is NOT re-enabled by the v7 upgrade');
    expect(settings.dragHintShown, isTrue);

    // 3c. Version bumped, still one row, and writes go through.
    final version = await db.customSelect('PRAGMA user_version').getSingle();
    expect(version.read<int>('user_version'), 8);
    expect(await db.select(db.settings).get(), hasLength(1));
    await db.into(db.settings).insertOnConflictUpdate(SettingsCompanion(
        id: const Value(1), showPassDevice: const Value(true)));
    expect((await db.select(db.settings).getSingle()).showPassDevice, isTrue);

    await db.close();
  });

  test('6 -> 8 upgrade adds rotate_board_hot_seat (=false) and preserves every '
      'v6 value — the shape on every tester device today', () async {
    // 1. Build a genuine v6 database: matches/games + the v6 settings table with
    //    a row the user had already edited — including the pass-device cover
    //    turned ON, which the v7 upgrade must leave alone (the two hot-seat
    //    settings are independent).
    final raw = sqlite3.openInMemory();
    raw.execute(_v1MatchesDdl);
    raw.execute(_v1GamesDdl);
    raw.execute(_v6SettingsDdl);
    raw.execute(
      'INSERT INTO settings (id, theme_mode, animation_speed, '
      'default_match_length, default_difficulty, tutor_override, '
      'show_highlights, enable_drag, enable_combined_taps, show_scoring, '
      'dice_roll_animation, show_pass_device, drag_hint_shown) '
      "VALUES (1, 'dark', 'normal', 7, 'hard', 'off', 1, 0, 1, 0, 1, 1, 1)",
    );
    raw.execute('PRAGMA user_version = 6');

    final cols = raw
        .select('PRAGMA table_info(settings)')
        .map((r) => r['name'] as String)
        .toSet();
    expect(cols, contains('show_pass_device'), reason: 'v6 has the cover col');
    expect(cols, isNot(contains('rotate_board_hot_seat')),
        reason: 'v6 predates the hot-seat rotation column');

    // 2. Open through AppDatabase (schemaVersion 8): onUpgrade(6 -> 7).
    final db = AppDatabase(NativeDatabase.opened(raw));

    // 3a. The column exists at its default — OFF, i.e. the tabletop layout an
    //     upgrading hot-seat player now gets, exactly as a fresh install does.
    final settings = await db.select(db.settings).getSingle();
    expect(settings.rotateBoardHotSeat, isFalse);

    // 3b. Every v6 value survived — in particular the pass-device cover the user
    //     had switched ON: it is INDEPENDENT of the rotation and works with
    //     either layout.
    expect(settings.showPassDevice, isTrue,
        reason: 'the v7 upgrade must not touch the pass-device setting');
    expect(settings.themeMode, 'dark');
    expect(settings.animationSpeed, 'normal');
    expect(settings.defaultMatchLength, 7);
    expect(settings.defaultDifficulty, 'hard');
    expect(settings.tutorOverride, 'off');
    expect(settings.showHighlights, isTrue);
    expect(settings.enableDrag, isFalse,
        reason: 'the one-time v4 drag flip must not re-run on a 6 -> 8 upgrade');
    expect(settings.enableCombinedTaps, isTrue);
    expect(settings.showScoring, isFalse);
    expect(settings.diceRollAnimation, isTrue);
    expect(settings.dragHintShown, isTrue);

    // 3c. Version bumped, still one row, and a save into the new column works
    //     (the failure mode a missing migration branch would produce).
    final version = await db.customSelect('PRAGMA user_version').getSingle();
    expect(version.read<int>('user_version'), 8);
    expect(await db.select(db.settings).get(), hasLength(1));
    await db.into(db.settings).insertOnConflictUpdate(SettingsCompanion(
        id: const Value(1), rotateBoardHotSeat: const Value(true)));
    expect((await db.select(db.settings).getSingle()).rotateBoardHotSeat,
        isTrue);

    await db.close();
  });

  test('7 -> 8 upgrade adds the online_session table and touches NOTHING else '
      '— the path every current install takes', () async {
    // 1. Build a genuine v7 database: matches/games with a real match row, and
    //    the v7 settings table holding a thoroughly edited row. v7 is what is
    //    on every device that has ever run a shipped build, so this is not a
    //    hypothetical rung on the ladder — it is THE upgrade.
    final raw = sqlite3.openInMemory();
    raw.execute(_v1MatchesDdl);
    raw.execute(_v1GamesDdl);
    raw.execute(_v7SettingsDdl);
    raw.execute(
      'INSERT INTO matches (created_at, match_length, mode, white_type, '
      "black_type) VALUES (1700000000, 7, 'vsComputer', 'human', 'ai:expert')",
    );
    raw.execute(
      'INSERT INTO settings (id, theme_mode, animation_speed, '
      'default_match_length, default_difficulty, tutor_override, '
      'show_highlights, enable_drag, enable_combined_taps, show_scoring, '
      'dice_roll_animation, show_pass_device, rotate_board_hot_seat, '
      'drag_hint_shown) '
      "VALUES (1, 'dark', 'slow', 11, 'hard', 'off', 0, 0, 0, 0, 0, 1, 1, 1)",
    );
    raw.execute('PRAGMA user_version = 7');

    final before = raw.select("SELECT name FROM sqlite_master WHERE type='table' "
        "AND name='online_session'");
    expect(before, isEmpty, reason: 'v7 predates the online-session table');

    // 2. Open through AppDatabase (schemaVersion 8): onUpgrade(7 -> 8).
    final db = AppDatabase(NativeDatabase.opened(raw));

    // 3a. The new table is there, seeded, and empty — the whole content of the
    //     v8 migration.
    final session = await db.select(db.onlineSession).getSingle();
    expect(session.id, 1);
    expect(session.uid, isNull);
    expect(session.refreshToken, isNull);
    expect(session.matchCode, isNull);

    // 3b. EVERY v7 settings value survived, bit for bit. v8 adds no settings
    //     column, so a single changed field here would mean a migration branch
    //     ran that had no business running — in particular the one-time v4 drag
    //     flip, which is gated on `from < 4` and must stay quiet at 7.
    final settings = await db.select(db.settings).getSingle();
    expect(settings.themeMode, 'dark');
    expect(settings.animationSpeed, 'slow');
    expect(settings.defaultMatchLength, 11);
    expect(settings.defaultDifficulty, 'hard');
    expect(settings.tutorOverride, 'off');
    expect(settings.showHighlights, isFalse);
    expect(settings.enableDrag, isFalse,
        reason: 'the v4 drag flip must not re-run on a 7 -> 8 upgrade');
    expect(settings.enableCombinedTaps, isFalse);
    expect(settings.showScoring, isFalse);
    expect(settings.diceRollAnimation, isFalse);
    expect(settings.showPassDevice, isTrue);
    expect(settings.rotateBoardHotSeat, isTrue);
    expect(settings.dragHintShown, isTrue);

    // 3c. The v1 match row is still there, and the version moved.
    final matches = await db.customSelect('SELECT * FROM matches').get();
    expect(matches, hasLength(1));
    expect(matches.single.read<int>('match_length'), 7);
    final version = await db.customSelect('PRAGMA user_version').getSingle();
    expect(version.read<int>('user_version'), 8);

    // 3d. And the table is usable, which is the failure a missing branch would
    //     have produced at the first sign-in.
    await db.into(db.onlineSession).insertOnConflictUpdate(
        OnlineSessionCompanion(id: const Value(1), uid: const Value('abc')));
    expect((await db.select(db.onlineSession).getSingle()).uid, 'abc');

    await db.close();
  });

  test('every upgrade path lands the v8 online_session table, seeded and empty',
      () async {
    // The table holds the durable anonymous identity. If a migration missed it,
    // the first sign-in would throw "no such table" and online play would be
    // dead for exactly the installs that already had history worth keeping — so
    // this walks EVERY shape the upgrade can start from.
    for (final start in <({String label, int version, List<String> ddl})>[
      (label: 'fresh install', version: 0, ddl: []),
      (label: 'v1', version: 1, ddl: [_v1MatchesDdl, _v1GamesDdl]),
      (
        label: 'v2',
        version: 2,
        ddl: [_v1MatchesDdl, _v1GamesDdl, _v2SettingsDdl]
      ),
      (
        label: 'v6',
        version: 6,
        ddl: [_v1MatchesDdl, _v1GamesDdl, _v6SettingsDdl]
      ),
      (
        label: 'v7',
        version: 7,
        ddl: [_v1MatchesDdl, _v1GamesDdl, _v7SettingsDdl]
      ),
    ]) {
      final raw = sqlite3.openInMemory();
      for (final ddl in start.ddl) {
        raw.execute(ddl);
      }
      if (start.version > 0) {
        raw.execute('PRAGMA user_version = ${start.version}');
      }
      final db = AppDatabase(NativeDatabase.opened(raw));

      // The row is seeded by beforeOpen and starts completely empty: no uid, no
      // token, and nothing to rejoin.
      final row = await db.select(db.onlineSession).getSingle();
      expect(row.id, 1, reason: '${start.label}: the single-row invariant');
      expect(row.uid, isNull, reason: '${start.label}: no identity yet');
      expect(row.refreshToken, isNull, reason: start.label);
      expect(row.matchCode, isNull, reason: start.label);

      final version = await db
          .customSelect('PRAGMA user_version')
          .map((r) => r.read<int>('user_version'))
          .getSingle();
      expect(version, 8, reason: '${start.label}: upgraded all the way');

      await db.close();
    }
  });
}
