import 'package:aigammon_app/data/database.dart';
import 'package:drift/drift.dart' show Value;
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:sqlite3/sqlite3.dart';

/// The exact v1 schema DDL (matches + games), as generated by drift at
/// schemaVersion 1 — before the v2 `settings` table existed. Embedded as a
/// constant so this test can materialise a genuine v1 database (raw sqlite3),
/// then open it through [AppDatabase] and prove the 1 -> N `onUpgrade` runs.
///
/// Column names/types mirror drift's output for the current `Matches`/`Games`
/// table definitions (unchanged since v1), so v1 rows round-trip after upgrade.
const _v1MatchesDdl = '''
CREATE TABLE "matches" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "created_at" INTEGER NOT NULL,
  "match_length" INTEGER NOT NULL,
  "mode" TEXT NOT NULL,
  "white_type" TEXT NOT NULL,
  "black_type" TEXT NOT NULL,
  "white_score" INTEGER NOT NULL DEFAULT 0,
  "black_score" INTEGER NOT NULL DEFAULT 0,
  "winner" TEXT NULL,
  "completed" INTEGER NOT NULL DEFAULT 0 CHECK ("completed" IN (0, 1))
);
''';

const _v1GamesDdl = '''
CREATE TABLE "games" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "match_id" INTEGER NOT NULL REFERENCES matches (id) ON DELETE CASCADE,
  "game_number" INTEGER NOT NULL,
  "is_crawford" INTEGER NOT NULL CHECK ("is_crawford" IN (0, 1)),
  "events_json" TEXT NOT NULL,
  "result_winner" TEXT NULL,
  "result_points" INTEGER NULL,
  "result_outcome" TEXT NULL,
  "analysis_json" TEXT NULL
);
''';

/// The exact v2 `settings` DDL — as drift generated it at schemaVersion 2,
/// BEFORE the v3 gameplay-option columns and the v4 `drag_hint_shown` column
/// existed. Embedded so this test can materialise a genuine v2 database and
/// prove the 2 -> 4 `onUpgrade` adds every later column.
const _v2SettingsDdl = '''
CREATE TABLE "settings" (
  "id" INTEGER NOT NULL DEFAULT 1,
  "theme_mode" TEXT NOT NULL DEFAULT 'system',
  "animation_speed" TEXT NOT NULL DEFAULT 'normal',
  "default_match_length" INTEGER NOT NULL DEFAULT 5,
  "default_difficulty" TEXT NOT NULL DEFAULT 'medium',
  "tutor_override" TEXT NULL,
  PRIMARY KEY ("id"),
  CHECK (id = 1)
);
''';

/// The exact v3 `settings` DDL — as drift generated it at schemaVersion 3. It
/// carries the four gameplay columns (`show_highlights`, `enable_drag`,
/// `enable_combined_taps`, `show_scoring`) but NOT the v4 `drag_hint_shown`
/// column, and crucially `enable_drag` still defaults to 0 (OFF) as it did in
/// v3. Embedded so this test can materialise a genuine v3 database and prove the
/// 3 -> 4 `onUpgrade` adds `drag_hint_shown` AND flips `enable_drag` to 1.
const _v3SettingsDdl = '''
CREATE TABLE "settings" (
  "id" INTEGER NOT NULL DEFAULT 1,
  "theme_mode" TEXT NOT NULL DEFAULT 'system',
  "animation_speed" TEXT NOT NULL DEFAULT 'normal',
  "default_match_length" INTEGER NOT NULL DEFAULT 5,
  "default_difficulty" TEXT NOT NULL DEFAULT 'medium',
  "tutor_override" TEXT NULL,
  "show_highlights" INTEGER NOT NULL DEFAULT 1 CHECK ("show_highlights" IN (0, 1)),
  "enable_drag" INTEGER NOT NULL DEFAULT 0 CHECK ("enable_drag" IN (0, 1)),
  "enable_combined_taps" INTEGER NOT NULL DEFAULT 1 CHECK ("enable_combined_taps" IN (0, 1)),
  "show_scoring" INTEGER NOT NULL DEFAULT 1 CHECK ("show_scoring" IN (0, 1)),
  PRIMARY KEY ("id"),
  CHECK (id = 1)
);
''';

void main() {
  test('fresh install (onCreate) seeds v4 defaults: drag ON, hint not shown',
      () async {
    // A brand-new database goes through onCreate (not onUpgrade): the v4 table
    // shape + the beforeOpen seed.
    final db = AppDatabase(NativeDatabase.memory());

    final settings = await db.select(db.settings).getSingle();
    expect(settings.enableDrag, isTrue,
        reason: 'drag-to-move is ON by default as of v4');
    expect(settings.dragHintShown, isFalse,
        reason: 'the one-time hint has not been shown yet on a fresh install');
    expect(settings.showHighlights, isTrue);
    expect(settings.enableCombinedTaps, isTrue);
    expect(settings.showScoring, isTrue);

    final version = await db.customSelect('PRAGMA user_version').getSingle();
    expect(version.read<int>('user_version'), 4);

    await db.close();
  });

  test('1 -> 4 upgrade creates the settings table whole (v4 shape: drag ON, '
      'drag_hint_shown present), seeds it, and preserves v1 data', () async {
    // 1. Build a genuine v1 database: the v1 tables, a real match row, and
    //    user_version = 1.
    final raw = sqlite3.openInMemory();
    raw.execute(_v1MatchesDdl);
    raw.execute(_v1GamesDdl);
    raw.execute(
      'INSERT INTO matches (created_at, match_length, mode, white_type, '
      "black_type) VALUES (1700000000, 5, 'vsComputer', 'human', 'ai:expert')",
    );
    raw.execute('PRAGMA user_version = 1');

    // Sanity: no settings table yet at v1.
    final before = raw.select(
        "SELECT name FROM sqlite_master WHERE type='table' AND name='settings'");
    expect(before, isEmpty, reason: 'v1 has no settings table');

    // 2. Open the SAME database through AppDatabase (schemaVersion 4). drift
    //    sees user_version 1 and runs onUpgrade(1 -> 4), then beforeOpen.
    final db = AppDatabase(NativeDatabase.opened(raw));

    // 3a. The settings table now exists with the single default row — including
    //     the v4 shape: drag ON (the new default), the hint not yet shown.
    final settings = await db.select(db.settings).getSingle();
    expect(settings.id, 1);
    expect(settings.themeMode, 'system');
    expect(settings.animationSpeed, 'normal');
    expect(settings.defaultMatchLength, 5);
    expect(settings.defaultDifficulty, 'medium');
    expect(settings.tutorOverride, isNull);
    expect(settings.showHighlights, isTrue);
    expect(settings.enableDrag, isTrue, reason: 'v4 default flips drag ON');
    expect(settings.enableCombinedTaps, isTrue);
    expect(settings.showScoring, isTrue);
    expect(settings.dragHintShown, isFalse);

    // 3b. The pre-migration v1 match row survived intact.
    final matches = await db.select(db.matches).get();
    expect(matches, hasLength(1));
    expect(matches.single.mode, 'vsComputer');
    expect(matches.single.matchLength, 5);
    expect(matches.single.whiteType, 'human');
    expect(matches.single.blackType, 'ai:expert');

    // 3c. The schema version was bumped to 4.
    final version = await db.customSelect('PRAGMA user_version').getSingle();
    expect(version.read<int>('user_version'), 4);

    // 3d. Writes still work post-migration (FK/insert into the migrated schema).
    final newId = await db.into(db.matches).insert(MatchesCompanion.insert(
          createdAt: DateTime.now(),
          matchLength: 3,
          mode: 'hotSeat',
          whiteType: 'human',
          blackType: 'human',
          whiteScore: const Value(0),
        ));
    expect(newId, greaterThan(matches.single.id));

    await db.close();
  });

  test('2 -> 4 upgrade adds the gameplay + drag_hint_shown columns, flips drag '
      'ON, and preserves the existing v2 settings row values', () async {
    // 1. Build a genuine v2 database: the matches/games tables (unchanged), the
    //    v2 settings table, a settings row with NON-default preferences, and
    //    user_version = 2.
    final raw = sqlite3.openInMemory();
    raw.execute(_v1MatchesDdl);
    raw.execute(_v1GamesDdl);
    raw.execute(_v2SettingsDdl);
    raw.execute(
      'INSERT INTO settings (id, theme_mode, animation_speed, '
      'default_match_length, default_difficulty, tutor_override) '
      "VALUES (1, 'dark', 'off', 7, 'expert', 'on')",
    );
    raw.execute('PRAGMA user_version = 2');

    // Sanity: the v2 settings table has none of the later columns yet.
    final cols = raw
        .select('PRAGMA table_info(settings)')
        .map((r) => r['name'] as String)
        .toSet();
    expect(cols, isNot(contains('show_highlights')), reason: 'v2 has no v3 cols');
    expect(cols, isNot(contains('enable_drag')));
    expect(cols, isNot(contains('drag_hint_shown')), reason: 'nor the v4 col');

    // 2. Open through AppDatabase (schemaVersion 4): drift runs onUpgrade(2 -> 4),
    //    adding the four gameplay columns + drag_hint_shown, then flipping drag.
    final db = AppDatabase(NativeDatabase.opened(raw));

    // 3a. The new columns exist at their v4 defaults on the migrated row —
    //     including drag flipped ON and the hint not yet shown.
    final settings = await db.select(db.settings).getSingle();
    expect(settings.showHighlights, isTrue);
    expect(settings.enableDrag, isTrue, reason: 'the v4 flip turns drag ON');
    expect(settings.enableCombinedTaps, isTrue);
    expect(settings.showScoring, isTrue);
    expect(settings.dragHintShown, isFalse);

    // 3b. The pre-existing v2 settings row values SURVIVED intact.
    expect(settings.id, 1);
    expect(settings.themeMode, 'dark');
    expect(settings.animationSpeed, 'off');
    expect(settings.defaultMatchLength, 7);
    expect(settings.defaultDifficulty, 'expert');
    expect(settings.tutorOverride, 'on');

    // 3c. The schema version was bumped to 4, and still exactly one row.
    final version = await db.customSelect('PRAGMA user_version').getSingle();
    expect(version.read<int>('user_version'), 4);
    expect(await db.select(db.settings).get(), hasLength(1));

    await db.close();
  });

  test('3 -> 4 upgrade adds drag_hint_shown (=false) and flips a user-OFF '
      'enable_drag to ON, preserving every other v3 value', () async {
    // 1. Build a genuine v3 database: matches/games + the v3 settings table with
    //    a row where the user deliberately turned drag OFF (enable_drag = 0) and
    //    tweaked other preferences. user_version = 3.
    final raw = sqlite3.openInMemory();
    raw.execute(_v1MatchesDdl);
    raw.execute(_v1GamesDdl);
    raw.execute(_v3SettingsDdl);
    raw.execute(
      'INSERT INTO settings (id, theme_mode, animation_speed, '
      'default_match_length, default_difficulty, tutor_override, '
      'show_highlights, enable_drag, enable_combined_taps, show_scoring) '
      "VALUES (1, 'dark', 'fast', 3, 'hard', 'off', 0, 0, 0, 0)",
    );
    raw.execute('PRAGMA user_version = 3');

    // Sanity: the v3 settings table has enable_drag (set OFF) but not the v4
    // drag_hint_shown column yet.
    final cols = raw
        .select('PRAGMA table_info(settings)')
        .map((r) => r['name'] as String)
        .toSet();
    expect(cols, contains('enable_drag'), reason: 'v3 has the gameplay cols');
    expect(cols, isNot(contains('drag_hint_shown')),
        reason: 'v3 predates the drag-hint column');

    // 2. Open through AppDatabase (schemaVersion 4): drift runs onUpgrade(3 -> 4),
    //    which addColumn's drag_hint_shown and UPDATEs enable_drag = 1.
    final db = AppDatabase(NativeDatabase.opened(raw));

    // 3a. drag_hint_shown now exists, defaulting false; enable_drag was flipped
    //     from the user's OFF back to ON (the one-time default flip).
    final settings = await db.select(db.settings).getSingle();
    expect(settings.dragHintShown, isFalse,
        reason: 'the drag_hint_shown column exists and starts false');
    expect(settings.enableDrag, isTrue,
        reason: 'the v4 upgrade flips a user-disabled drag back ON (one-time)');

    // 3b. Every OTHER v3 value survived untouched — the flip is surgical.
    expect(settings.themeMode, 'dark');
    expect(settings.animationSpeed, 'fast');
    expect(settings.defaultMatchLength, 3);
    expect(settings.defaultDifficulty, 'hard');
    expect(settings.tutorOverride, 'off');
    expect(settings.showHighlights, isFalse);
    expect(settings.enableCombinedTaps, isFalse);
    expect(settings.showScoring, isFalse);

    // 3c. The schema version was bumped to 4, still exactly one row.
    final version = await db.customSelect('PRAGMA user_version').getSingle();
    expect(version.read<int>('user_version'), 4);
    expect(await db.select(db.settings).get(), hasLength(1));

    // 3d. Writes still work post-migration (upsert the migrated settings row).
    await db.into(db.settings).insertOnConflictUpdate(
        SettingsCompanion(id: const Value(1), dragHintShown: const Value(true)));
    expect((await db.select(db.settings).getSingle()).dragHintShown, isTrue);

    await db.close();
  });
}
