/// Generates `lib/src/met.dart` from the vendored gnubg MET XML.
///
/// Run from the package root (`packages/engine_bindings`):
///
///     dart run tool/generate_met.dart
///
/// Output is deterministic: running twice produces byte-identical output. The
/// generated file has zero runtime dependencies (only `const` collections).
library;

import 'dart:io';

import 'met_parser.dart';

const _xmlPath = 'assets/met/Kazaross-XG2.xml';
const _outPath = 'lib/src/met.dart';
const _sourceUrl =
    'https://raw.githubusercontent.com/mormegil-cz/gnubg/master/met/Kazaross-XG2.xml';
const _fetchDate = '2026-07-25';

void main() {
  final xml = File(_xmlPath).readAsStringSync();
  final met = parseMetXml(xml);

  // Fail loudly if the data is not oriented/consistent as expected.
  validateMet(met);

  final out = _render(met);
  File(_outPath).writeAsStringSync(out);
  stdout.writeln('Wrote $_outPath '
      '(maxAway=${met.length}, ${met.length}x${met.length} pre-Crawford, '
      '${met.length} post-Crawford).');
}

String _render(ParsedMet met) {
  String d(double v) {
    // Dart's double.toString() yields the shortest string that round-trips to
    // the identical double, so the generated literals reparse exactly (this is
    // what makes the drift-guard test pass and generation idempotent).
    final s = v.toString();
    return s.contains('.') || s.contains('e') || s.contains('E') ? s : '$s.0';
  }

  final b = StringBuffer();
  b.writeln('// GENERATED by tool/generate_met.dart from '
      'assets/met/Kazaross-XG2.xml — do not edit.');
  b.writeln('//');
  b.writeln('// Source: $_sourceUrl');
  b.writeln('// Fetched: $_fetchDate');
  b.writeln('// Data: unmodified gnubg "Kazaross XG2 25 point MET" (numeric');
  b.writeln('// match-equity table). Regenerate with: '
      'dart run tool/generate_met.dart');
  b.writeln();
  b.writeln('/// Kazaross-XG2 match equity table (gnubg default).');
  b.writeln('///');
  b.writeln('/// [preCrawford] gives the probability that the player who is');
  b.writeln('/// `awayA` points from victory beats the player `awayB` away, at');
  b.writeln('/// the start of a game, pre-Crawford. [postCrawford] gives the');
  b.writeln('/// probability that the trailer `away` away wins from the start of');
  b.writeln('/// a post-Crawford game. Both are 1-indexed by away score.');
  b.writeln('class MatchEquityTable {');
  b.writeln('  MatchEquityTable._();');
  b.writeln();
  b.writeln('  /// Largest supported "away" score (gnubg table length).');
  b.writeln('  static const int maxAway = ${met.length};');
  b.writeln();
  b.writeln('  /// Pre-Crawford equity for the player [awayA] away against an');
  b.writeln('  /// opponent [awayB] away. Both must be in `1..maxAway`.');
  b.writeln('  static double preCrawford(int awayA, int awayB) {');
  b.writeln('    if (awayA < 1 || awayA > maxAway) {');
  b.writeln("      throw ArgumentError.value(awayA, 'awayA', "
      "'must be in 1..\$maxAway');");
  b.writeln('    }');
  b.writeln('    if (awayB < 1 || awayB > maxAway) {');
  b.writeln("      throw ArgumentError.value(awayB, 'awayB', "
      "'must be in 1..\$maxAway');");
  b.writeln('    }');
  b.writeln('    return _preCrawford[awayA - 1][awayB - 1];');
  b.writeln('  }');
  b.writeln();
  b.writeln('  /// Post-Crawford equity for the trailer [away] away. Must be in');
  b.writeln('  /// `1..maxAway`.');
  b.writeln('  static double postCrawford(int away) {');
  b.writeln('    if (away < 1 || away > maxAway) {');
  b.writeln("      throw ArgumentError.value(away, 'away', "
      "'must be in 1..\$maxAway');");
  b.writeln('    }');
  b.writeln('    return _postCrawford[away - 1];');
  b.writeln('  }');
  b.writeln();
  b.writeln('  static const List<List<double>> _preCrawford = <List<double>>[');
  for (final row in met.preCrawford) {
    b.writeln('    <double>[${row.map(d).join(', ')}],');
  }
  b.writeln('  ];');
  b.writeln();
  b.writeln('  static const List<double> _postCrawford = <double>[');
  // Chunk the single post row for readability.
  const perLine = 5;
  for (var i = 0; i < met.postCrawford.length; i += perLine) {
    final chunk = met.postCrawford
        .sublist(i, (i + perLine).clamp(0, met.postCrawford.length));
    b.writeln('    ${chunk.map(d).join(', ')},');
  }
  b.writeln('  ];');
  b.writeln('}');
  return b.toString();
}
